package controller.pub;

import jakarta.servlet.RequestDispatcher;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import model.bean.ProductAdminDetail;

import java.io.IOException;
import java.util.ArrayList;

public class CartController extends HttpServlet {
	private static final long serialVersionUID = 1L;
    public CartController() {
        super();
    }
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		RequestDispatcher rd = request.getRequestDispatcher("/public/cart_page.jsp");
		rd.forward(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		HttpSession session = request.getSession();
		ArrayList<ProductAdminDetail> listPro = (ArrayList<ProductAdminDetail>)session.getAttribute("listPro1");
		int id=0;
		if(request.getParameter("amount-edit")!=null&&request.getParameter("id-product")!=null) {
			int product_id = Integer.parseInt(request.getParameter("id-product"));
			int qty = Integer.parseInt(request.getParameter("amount-edit"));
			for (ProductAdminDetail productAdminDetail : listPro) {
				if(productAdminDetail.getId()==product_id) {
					productAdminDetail.setAmount(qty);
				}
			}
			float sum_price=0;
			if(listPro.size()>0) {
				response.getWriter().print("<div class=\"main container cartpcstyle\">\r\n"
						+ "		<div class=\"wrap_background_aside margin-bottom-40\">\r\n"
						+ "			<div class=\"cart-page\">\r\n"
						+ "				<div class=\"drawer__inner\">\r\n"
						+ "					<div class=\"CartPageContainer\">\r\n"
						+ "	<form action=\""+request.getContextPath()+"/public/checkout-page\" method=\"post\" novalidate=\"\" class=\"cart ajaxcart cartpage container\">\r\n"
						+ "		<div class=\"row1\">\r\n"
						+ "			<div class=\"col-12 col-xl-8 order-1 order-xl-1\">\r\n"
						+ "				<div class=\"ajaxcart__inner ajaxcart__inner--has-fixed-footer cart_body items\">\r\n"
						+ "					<p class=\"title\"><span class=\"text-uppercase\">Giỏ hàng</span><span class=\"total-cart\">(<span class=\"count_item_pr\">"+listPro.size()+"</span>) Sản phẩm<span></span></span></p>\r\n"
						+ "					<div class=\"cart-header-info d-none d-md-flex\">\r\n"
						+ "						<div>Sản phẩm</div><div>Đơn giá</div><div>Số lượng</div><div>Tổng tiền</div>\r\n"
						+ "					</div>				\r\n"
						+ "					<div class=\"items-available\">\r\n"
						+ "						<div class=\"ajaxcart__row cart-item  \">");
				for (ProductAdminDetail objPr : listPro) {
					sum_price =(float) (sum_price + (objPr.getPrice()*objPr.getAmount()));
					response.getWriter().print("<div class=\"ajaxcart__product cart_product\" data-line=\"1\">\r\n"
							+ "								<a href=\"#\" class=\"ajaxcart__product-image cart_image\" title=\""+objPr.getName()+"\"><img src=\""+request.getContextPath()+"/templates/admin/assets/images/table/product/"+objPr.getImages()+"\" alt=\""+objPr.getName()+"\"></a>\r\n"
							+ "								<div class=\"grid__item cart_info\">\r\n"
							+ "									<div class=\"ajaxcart__product-name-wrapper cart_name\">\r\n"
							+ "										<a href=\"#\" class=\"ajaxcart__product-name h4\" title=\""+objPr.getName()+"\">"+objPr.getName()+"</a>\r\n"
							+ "										<span class=\"ajaxcart__product-meta variant-title d-none d-md-block\">"+objPr.getColor()+" / "+objPr.getSize()+"</span>\r\n"
							+ "									</div>\r\n"
							+ "									<div class=\"grid grid-price-1\">\r\n"
							+ "										<div class=\"grid__item one-half text-center cart_prices\">\r\n"
							+ "												<span class=\"cart-price \">"+(int)objPr.getPrice() +"đ</span>\r\n"
							+ "										</div>\r\n"
							+ "									</div>\r\n"
							+ "									<div class=\"grid grid-qty\">\r\n"
							+ "											<span class=\"ajaxcart__product-meta variant-title-mobile d-md-none\">"+objPr.getColor() +" / "+objPr.getSize() +"</span>\r\n"
							+ "										<div class=\"grid__item one-half cart_select\">\r\n"
							+ "											<div class=\"ajaxcart__qty input-group-btn\">\r\n"
							+ "												<button type=\"button\" class=\"ajaxcart__qty-adjust ajaxcart__qty--minus items-count btn-minus"+objPr.getId()+"\" data-id=\"\" data-qty=\"1\" data-line=\"1\" aria-label=\"-\">\r\n"
							+ "													-\r\n"
							+ "												</button>\r\n"
							+ "												<input type=\"text\" name=\"amount\" class=\"ajaxcart__qty-num number-sidebar edit_amount\" data-id=\""+objPr.getId()+"\" id=\"qty"+objPr.getId()+"\" value=\""+objPr.getAmount()+"\" min=\"0\" data-id=\"\" type=\"number\">"
							+ "												<button type=\"button\" class=\"ajaxcart__qty-adjust ajaxcart__qty--plus items-count btn-plus"+objPr.getId()+"\" data-id=\"\" data-line=\"1\" data-qty=\"3\" aria-label=\"+\">\r\n"
							+ "													+			\r\n"
							+ "												</button>\r\n"
							+ "											</div>\r\n"
							+ "										</div>\r\n"
							+ "									</div>\r\n"
							+ "									<div class=\"grid grid-price grid-price-2\">\r\n"
							+ "										<p class=\"remove-cart\"><a class=\"cart__btn-remove remove-item-cart ajaxifyCart--remove\" id=\"del-cart"+objPr.getId()+"\" href=\"javascript: void(0)\" data-valuecart=\""+objPr.getId() +"\" ></a></p>\r\n"
							+ "									</div>\r\n"
							+ "									</div>\r\n"
							+ "									<script>\r\n"
							+ "										$('.btn-plus"+objPr.getId()+"').on('click', function(e) {\r\n"
							+ "											var num = parseInt($('#qty"+objPr.getId()+"').val());\r\n"
							+ "												var newNum = num+1;\r\n"
							+ "												$('#qty"+objPr.getId() +"').val(newNum);\r\n"
							+ "										});\r\n"
							+ "									$('.btn-minus"+objPr.getId()+"').on('click', function(e) {\r\n"
							+ "										var num = parseInt($('#qty"+objPr.getId()+"').val());\r\n"
							+ "										if(num>=1){\r\n"
							+ "											var newNum = num-1;\r\n"
							+ "											$('#qty"+objPr.getId()+"').val(newNum);\r\n"
							+ "										}\r\n"
							+ "									});"
							+ "										$(function() {\r\n"
							+ "										    $('#del-cart"+objPr.getId()+"').on('click', function() {\r\n"
							+ "										        var changedField = $(this);\r\n"
							+ "										        var id = $(this).data(\"valuecart\");\r\n"
							+ "										        $.ajax({\r\n"
							+ "													url: '"+request.getContextPath()+"/public/cart',\r\n"
							+ "													type: 'POST',\r\n"
							+ "													cache: false,\r\n"
							+ "													data: {aid: id, },\r\n"
							+ "													success: function(data){\r\n"
							+ "														$('.ajax-cart1').html(data);\r\n"
							+ "													},\r\n"
							+ "													error: function (){\r\n"
							+ "														alert('Có lỗi xảy ra');\r\n"
							+ "													}\r\n"
							+ "												});\r\n"
							+ "												 $.ajax({\r\n"
							+ "													url: '"+request.getContextPath()+"/public/handel-cart',\r\n"
							+ "													type: 'POST',\r\n"
							+ "													cache: false,\r\n"
							+ "													data: {aid: id, },\r\n"
							+ "													success: function(data){\r\n"
							+ "														$('.ajax-cart').html(data);\r\n"
							+ "													},\r\n"
							+ "													error: function (){\r\n"
							+ "														alert('Có lỗi xảy ra');\r\n"
							+ "													}\r\n"
							+ "												});"
							+ "										    });\r\n"
							+ "											$('.edit_amount').on('change', function() {\r\n"
							+ "										        var changedField = $(this);\r\n"
							+ "										        var id = $(this).data('id');\r\n"
							+ "										        var qty = $(this).val();\r\n"
							+ "										        $.ajax({\r\n"
							+ "													url: '"+request.getContextPath()+"/public/cart',\r\n"
							+ "													type: 'POST',\r\n"
							+ "													cache: false,\r\n"
							+ "													data: {\r\n"
							+ "														'id-product': id,\r\n"
							+ "														'amount-edit':qty,\r\n"
							+ "														},\r\n"
							+ "													success: function(data){\r\n"
							+ "														$('.ajax-cart1').html(data);\r\n"
							+ "													},\r\n"
							+ "													error: function (){\r\n"
							+ "														alert('Có lỗi xảy ra');\r\n"
							+ "													}\r\n"
							+ "												});\r\n"
							+ "										        $.ajax({\r\n"
							+ "													url: '"+request.getContextPath()+"/public/handel-cart',\r\n"
							+ "													type: 'POST',\r\n"
							+ "													cache: false,\r\n"
							+ "													data: {\r\n"
							+ "														'id-product': id,\r\n"
							+ "														'amount-edit':qty, },\r\n"
							+ "													success: function(data){\r\n"
							+ "														$('.ajax-cart').html(data);\r\n"
							+ "													},\r\n"
							+ "													error: function (){\r\n"
							+ "														alert('Có lỗi xảy ra');\r\n"
							+ "													}\r\n"
							+ "												});\r\n"
							+ "										    });"
							+ "										});\r\n"
							+ "								</script>"
							+ "								</div>");
				}
				response.getWriter().print("</div>\r\n"
						+ "					</div>\r\n"
						+ "				</div>	\r\n"
						+ "			</div>\r\n"
						+ "			<div class=\"col-12 col-xl-4 order-3 order-xl-2 ajaxcart__wrap-footer\">\r\n"
						+ "				<div class=\"ajaxcart__footer ajaxcart__footer--fixed cart-footer\">\r\n"
						+ "					<div class=\"ajaxcart__subtotal\">\r\n"
						+ "						<div class=\"cart__subtotal\">\r\n"
						+ "							<div class=\"cart__col-6\">Tổng đơn hàng (Tạm tính) :</div>\r\n"
						+ "							<div class=\"text-right cart__totle\"><span class=\"total-price\">"+(int)sum_price+"</span></div>\r\n"
						+ "						</div>\r\n"
						+ "					</div>\r\n"
						+ "					<div class=\"cart__btn-proceed-checkout-dt\">\r\n"
						+ "						<button type=\"submit\" class=\"button btn btn-default cart__btn-proceed-checkout\" id=\"btn-proceed-checkout\" title=\"Thanh toán\"><span class=\"text-payment\">Đặt hàng</span> (<span class=\"count_item_pr\">"+listPro.size()+"</span>)</button>\r\n"
						+ "					</div>\r\n"
						+ "				</div>\r\n"
						+ "			</div>\r\n"
						+ "		</div>\r\n"
						+ "	</form>\r\n"
						+ "	<script>\r\n"
						+ "		function getRndInteger(min, max) {\r\n"
						+ "			  return Math.floor(Math.random() * (max - min + 1) ) + min;\r\n"
						+ "			}\r\n"
						+ "		if(!localStorage.getItem(\"count\")) {\r\n"
						+ "			localStorage.setItem(\"count\", getRndInteger(80,150))\r\n"
						+ "		}\r\n"
						+ "		var x = localStorage.getItem(\"count\")\r\n"
						+ "		$(\"#count-customer\").html(x);\r\n"
						+ "		\r\n"
						+ "	</script>\r\n"
						+ "			</div>\r\n"
						+ "				</div>\r\n"
						+ "			</div>\r\n"
						+ "		</div>\r\n"
						+ "	</div>");
				}else {
					response.getWriter().print("<div class=\"main container cartpcstyle\">\r\n"
							+ "		<div class=\"wrap_background_aside margin-bottom-40\">\r\n"
							+ "			<div class=\"cart-page\">\r\n"
							+ "				<div class=\"drawer__inner\">\r\n"
							+ "					<div class=\"CartPageContainer\">\r\n"
							+ "						<form action=\""+request.getContextPath()+"/public/list-order\" method=\"post\" class=\"cart cartpage container\">\r\n"
							+ "							<div class=\"row1\">\r\n"
							+ "								<div class=\"col-12 col-xl-8 order-1 order-xl-1\">\r\n"
							+ "									<div class=\"ajaxcart__inner ajaxcart__inner--has-fixed-footer cart_body items\">\r\n"
							+ "										<p class=\"title\"><span class=\"text-uppercase\">Giỏ hàng</span><span class=\"total-cart\">(<span class=\"count_item_pr\">0</span>) Sản phẩm<span></span></span></p>\r\n"
							+ "										<div class=\"cart-header-info d-none d-md-flex\">\r\n"
							+ "											<div>Sản phẩm</div><div>Đơn giá</div><div>Số lượng</div><div>Tổng tiền</div>\r\n"
							+ "										</div>				\r\n"
							+ "										<div class=\"items-available\">\r\n"
							+ "											<div class=\"ajaxcart__row cart-item  \">\r\n"
							+ "												<p>Không có đơn hàng hãy đặt hàng</p>\r\n"
							+ "											</div>\r\n"
							+ "										</div>\r\n"
							+ "									</div>\r\n"
							+ "								</div>\r\n"
							+ "								<div class=\"col-12 col-xl-4 order-3 order-xl-2 ajaxcart__wrap-footer\">\r\n"
							+ "									<div class=\"ajaxcart__footer ajaxcart__footer--fixed cart-footer\">\r\n"
							+ "										<div class=\"ajaxcart__subtotal\">\r\n"
							+ "											<div class=\"cart__subtotal\">\r\n"
							+ "												<div class=\"cart__col-6\">Tra cứu đơn hàng: </div>\r\n"
							+ "												<div class=\"text-right cart__totle\"><input type=\"text\" name=\"order_code\" value=\"\" required=\"required\"></div>\r\n"
							+ "											</div>\r\n"
							+ "										</div>\r\n"
							+ "										<div class=\"cart__btn-proceed-checkout-dt\">\r\n"
							+ "											<button type=\"submit\" class=\"button btn btn-default cart__btn-proceed-checkout\" id=\"btn-proceed-checkout\" title=\"Thanh toán\"><span class=\"text-payment\">Tra Cứu</span></button>\r\n"
							+ "										</div>\r\n"
							+ "									</div>\r\n"
							+ "								</div>"
							+ "							</div>\r\n"
							+ "						</form>\r\n"
							+ "					</div>\r\n"
							+ "				</div>\r\n"
							+ "			</div>\r\n"
							+ "		</div>\r\n"
							+ "	</div>\r\n"
							+ "	<script>\r\n"
							+ "		function getRndInteger(min, max) {\r\n"
							+ "			  return Math.floor(Math.random() * (max - min + 1) ) + min;\r\n"
							+ "			}\r\n"
							+ "		if(!localStorage.getItem(\"count\")) {\r\n"
							+ "			localStorage.setItem(\"count\", getRndInteger(80,150))\r\n"
							+ "		}\r\n"
							+ "		var x = localStorage.getItem(\"count\")\r\n"
							+ "		$(\"#count-customer\").html(x);\r\n"
							+ "	</script>\r\n"
							+ "			</div>\r\n"
							+ "				</div>\r\n"
							+ "			</div>\r\n"
							+ "		</div>\r\n"
							+ "	</div>");
				}
			}else {
				if(request.getParameter("aid")!=null) {
					id = Integer.parseInt(request.getParameter("aid"));
					float sum_price = 0;
					if(listPro.size()>0) {
						for(int i = 0; i<listPro.size(); i++) {
							if(listPro.get(i).getId()==id) {
								listPro.remove(listPro.get(i));
							}
						}
					}
						if(listPro.size()>0) {
							response.getWriter().print("<div class=\"main container cartpcstyle\">\r\n"
									+ "		<div class=\"wrap_background_aside margin-bottom-40\">\r\n"
									+ "			<div class=\"cart-page\">\r\n"
									+ "				<div class=\"drawer__inner\">\r\n"
									+ "					<div class=\"CartPageContainer\">\r\n"
									+ "	<form action=\""+request.getContextPath()+"/public/checkout-page\" method=\"post\" novalidate=\"\" class=\"cart ajaxcart cartpage container\">\r\n"
									+ "		<div class=\"row1\">\r\n"
									+ "			<div class=\"col-12 col-xl-8 order-1 order-xl-1\">\r\n"
									+ "				<div class=\"ajaxcart__inner ajaxcart__inner--has-fixed-footer cart_body items\">\r\n"
									+ "					<p class=\"title\"><span class=\"text-uppercase\">Giỏ hàng</span><span class=\"total-cart\">(<span class=\"count_item_pr\">"+listPro.size()+"</span>) Sản phẩm<span></span></span></p>\r\n"
									+ "					<div class=\"cart-header-info d-none d-md-flex\">\r\n"
									+ "						<div>Sản phẩm</div><div>Đơn giá</div><div>Số lượng</div><div>Tổng tiền</div>\r\n"
									+ "					</div>				\r\n"
									+ "					<div class=\"items-available\">\r\n"
									+ "						<div class=\"ajaxcart__row cart-item  \">");
							for (ProductAdminDetail objPr : listPro) {
								sum_price =(float) (sum_price + (objPr.getPrice()*objPr.getAmount()));
								response.getWriter().print("<div class=\"ajaxcart__product cart_product\" data-line=\"1\">\r\n"
										+ "								<a href=\"#\" class=\"ajaxcart__product-image cart_image\" title=\""+objPr.getName()+"\"><img src=\""+request.getContextPath()+"/templates/admin/assets/images/table/product/"+objPr.getImages()+"\" alt=\""+objPr.getName()+"\"></a>\r\n"
										+ "								<div class=\"grid__item cart_info\">\r\n"
										+ "									<div class=\"ajaxcart__product-name-wrapper cart_name\">\r\n"
										+ "										<a href=\"#\" class=\"ajaxcart__product-name h4\" title=\""+objPr.getName()+"\">"+objPr.getName()+"</a>\r\n"
										+ "										<span class=\"ajaxcart__product-meta variant-title d-none d-md-block\">"+objPr.getColor()+" / "+objPr.getSize()+"</span>\r\n"
										+ "									</div>\r\n"
										+ "									<div class=\"grid grid-price-1\">\r\n"
										+ "										<div class=\"grid__item one-half text-center cart_prices\">\r\n"
										+ "												<span class=\"cart-price \">"+(int)objPr.getPrice() +"đ</span>\r\n"
										+ "										</div>\r\n"
										+ "									</div>\r\n"
										+ "									<div class=\"grid grid-qty\">\r\n"
										+ "											<span class=\"ajaxcart__product-meta variant-title-mobile d-md-none\">"+objPr.getColor() +" / "+objPr.getSize() +"</span>\r\n"
										+ "										<div class=\"grid__item one-half cart_select\">\r\n"
										+ "											<div class=\"ajaxcart__qty input-group-btn\">\r\n"
										+ "												<button type=\"button\" class=\"ajaxcart__qty-adjust ajaxcart__qty--minus items-count btn-minus"+objPr.getId()+"\" data-id=\"\" data-qty=\"1\" data-line=\"1\" aria-label=\"-\">\r\n"
										+ "													-\r\n"
										+ "												</button>\r\n"
										+ "												<input type=\"text\" name=\"amount\" class=\"ajaxcart__qty-num number-sidebar edit_amount\" data-id=\""+objPr.getId()+"\" id=\"qty"+objPr.getId()+"\" value=\""+objPr.getAmount()+"\" min=\"0\" data-id=\"\" type=\"number\" >\r\n"
										+ "												<button type=\"button\" class=\"ajaxcart__qty-adjust ajaxcart__qty--plus items-count btn-plus"+objPr.getId()+"\" data-id=\"\" data-line=\"1\" data-qty=\"3\" aria-label=\"+\">\r\n"
										+ "													+			\r\n"
										+ "												</button>\r\n"
										+ "											</div>\r\n"
										+ "										</div>\r\n"
										+ "									</div>\r\n"
										+ "									<div class=\"grid grid-price grid-price-2\">\r\n"
										+ "										<p class=\"remove-cart\"><a class=\"cart__btn-remove remove-item-cart ajaxifyCart--remove\" id=\"del-cart"+objPr.getId()+"\" href=\"javascript: void(0)\" data-valuecart=\""+objPr.getId() +"\" ></a></p>\r\n"
										+ "									</div>\r\n"
										+ "									</div>\r\n"
										+ "									<script>\r\n"
										+ "										$(function() {\r\n"
										+ "										$('.btn-plus"+objPr.getId()+"').on('click', function(e) {\r\n"
										+ "											var num = parseInt($('#qty"+objPr.getId()+"').val());\r\n"
										+ "												var newNum = num+1;\r\n"
										+ "												$('#qty"+objPr.getId() +"').val(newNum);\r\n"
										+ "										});\r\n"
										+ "									$('.btn-minus"+objPr.getId()+"').on('click', function(e) {\r\n"
										+ "										var num = parseInt($('#qty"+objPr.getId()+"').val());\r\n"
										+ "										if(num>=1){\r\n"
										+ "											var newNum = num-1;\r\n"
										+ "											$('#qty"+objPr.getId()+"').val(newNum);\r\n"
										+ "										}\r\n"
										+ "									});"
										+ "										    $('#del-cart"+objPr.getId()+"').on('click', function() {\r\n"
										+ "										        var changedField = $(this);\r\n"
										+ "										        var id = $(this).data(\"valuecart\");\r\n"
										+ "										        $.ajax({\r\n"
										+ "													url: '"+request.getContextPath()+"/public/cart',\r\n"
										+ "													type: 'POST',\r\n"
										+ "													cache: false,\r\n"
										+ "													data: {aid: id, },\r\n"
										+ "													success: function(data){\r\n"
										+ "														$('.ajax-cart1').html(data);\r\n"
										+ "													},\r\n"
										+ "													error: function (){\r\n"
										+ "														alert('Có lỗi xảy ra');\r\n"
										+ "													}\r\n"
										+ "												});\r\n"
										+ "												 $.ajax({\r\n"
										+ "													url: '"+request.getContextPath()+"/public/handel-cart',\r\n"
										+ "													type: 'POST',\r\n"
										+ "													cache: false,\r\n"
										+ "													data: {aid: id, },\r\n"
										+ "													success: function(data){\r\n"
										+ "														$('.ajax-cart').html(data);\r\n"
										+ "													},\r\n"
										+ "													error: function (){\r\n"
										+ "														alert('Có lỗi xảy ra');\r\n"
										+ "													}\r\n"
										+ "												});"
										+ "										    });\r\n"
										+ "											$('.edit_amount').on('change', function() {\r\n"
										+ "										        var changedField = $(this);\r\n"
										+ "										        var id = $(this).data(\"id\");\r\n"
										+ "										        var qty = $(this).val();\r\n"
										+ "										        $.ajax({\r\n"
										+ "													url: '"+request.getContextPath()+"/public/cart',\r\n"
										+ "													type: 'POST',\r\n"
										+ "													cache: false,\r\n"
										+ "													data: {\r\n"
										+ "														'id-product': id,\r\n"
										+ "														'amount-edit':qty,\r\n"
										+ "														},\r\n"
										+ "													success: function(data){\r\n"
										+ "														$('.ajax-cart1').html(data);\r\n"
										+ "													},\r\n"
										+ "													error: function (){\r\n"
										+ "														alert('Có lỗi xảy ra');\r\n"
										+ "													}\r\n"
										+ "												});\r\n"
										+ "										        $.ajax({\r\n"
										+ "													url: '"+request.getContextPath()+"/public/handel-cart',\r\n"
										+ "													type: 'POST',\r\n"
										+ "													cache: false,\r\n"
										+ "													data: {\r\n"
										+ "														'id-product': id,\r\n"
										+ "														'amount-edit':qty, },\r\n"
										+ "													success: function(data){\r\n"
										+ "														$('.ajax-cart').html(data);\r\n"
										+ "													},\r\n"
										+ "													error: function (){\r\n"
										+ "														alert('Có lỗi xảy ra');\r\n"
										+ "													}\r\n"
										+ "												});\r\n"
										+ "										    });"
										+ "										});\r\n"
										+ "								</script>"
										+ "								</div>");
							}
							response.getWriter().print("</div>\r\n"
									+ "					</div>\r\n"
									+ "				</div>	\r\n"
									+ "			</div>\r\n"
									+ "			<div class=\"col-12 col-xl-4 order-3 order-xl-2 ajaxcart__wrap-footer\">\r\n"
									+ "				<div class=\"ajaxcart__footer ajaxcart__footer--fixed cart-footer\">\r\n"
									+ "					<div class=\"ajaxcart__subtotal\">\r\n"
									+ "						<div class=\"cart__subtotal\">\r\n"
									+ "							<div class=\"cart__col-6\">Tổng đơn hàng (Tạm tính) :</div>\r\n"
									+ "							<div class=\"text-right cart__totle\"><span class=\"total-price\">"+(int)sum_price+"</span></div>\r\n"
									+ "						</div>\r\n"
									+ "					</div>\r\n"
									+ "					<div class=\"cart__btn-proceed-checkout-dt\">\r\n"
									+ "						<button type=\"submit\" class=\"button btn btn-default cart__btn-proceed-checkout\" id=\"btn-proceed-checkout\" title=\"Thanh toán\"><span class=\"text-payment\">Đặt hàng</span> (<span class=\"count_item_pr\">"+listPro.size()+"</span>)</button>\r\n"
									+ "					</div>\r\n"
									+ "				</div>\r\n"
									+ "			</div>\r\n"
									+ "		</div>\r\n"
									+ "	</form>\r\n"
									+ "	<script>\r\n"
									+ "		function getRndInteger(min, max) {\r\n"
									+ "			  return Math.floor(Math.random() * (max - min + 1) ) + min;\r\n"
									+ "			}\r\n"
									+ "		if(!localStorage.getItem(\"count\")) {\r\n"
									+ "			localStorage.setItem(\"count\", getRndInteger(80,150))\r\n"
									+ "		}\r\n"
									+ "		var x = localStorage.getItem(\"count\")\r\n"
									+ "		$(\"#count-customer\").html(x);\r\n"
									+ "		\r\n"
									+ "	</script>\r\n"
									+ "			</div>\r\n"
									+ "				</div>\r\n"
									+ "			</div>\r\n"
									+ "		</div>\r\n"
									+ "	</div>");
						}else {
							response.getWriter().print("<div class=\"main container cartpcstyle\">\r\n"
									+ "		<div class=\"wrap_background_aside margin-bottom-40\">\r\n"
									+ "			<div class=\"cart-page\">\r\n"
									+ "				<div class=\"drawer__inner\">\r\n"
									+ "					<div class=\"CartPageContainer\">\r\n"
									+ "						<form action=\""+request.getContextPath()+"/public/list-order\" method=\"post\" class=\"cart cartpage container\">\r\n"
									+ "							<div class=\"row1\">\r\n"
									+ "								<div class=\"col-12 col-xl-8 order-1 order-xl-1\">\r\n"
									+ "									<div class=\"ajaxcart__inner ajaxcart__inner--has-fixed-footer cart_body items\">\r\n"
									+ "										<p class=\"title\"><span class=\"text-uppercase\">Giỏ hàng</span><span class=\"total-cart\">(<span class=\"count_item_pr\">0</span>) Sản phẩm<span></span></span></p>\r\n"
									+ "										<div class=\"cart-header-info d-none d-md-flex\">\r\n"
									+ "											<div>Sản phẩm</div><div>Đơn giá</div><div>Số lượng</div><div>Tổng tiền</div>\r\n"
									+ "										</div>				\r\n"
									+ "										<div class=\"items-available\">\r\n"
									+ "											<div class=\"ajaxcart__row cart-item  \">\r\n"
									+ "												<p>Không có đơn hàng hãy đặt hàng</p>\r\n"
									+ "											</div>\r\n"
									+ "										</div>\r\n"
									+ "									</div>\r\n"
									+ "								</div>\r\n"
									+ "								<div class=\"col-12 col-xl-4 order-3 order-xl-2 ajaxcart__wrap-footer\">\r\n"
									+ "									<div class=\"ajaxcart__footer ajaxcart__footer--fixed cart-footer\">\r\n"
									+ "										<div class=\"ajaxcart__subtotal\">\r\n"
									+ "											<div class=\"cart__subtotal\">\r\n"
									+ "												<div class=\"cart__col-6\">Tra cứu đơn hàng: </div>\r\n"
									+ "												<div class=\"text-right cart__totle\"><input type=\"text\" name=\"order_code\" value=\"\" required=\"required\"></div>\r\n"
									+ "											</div>\r\n"
									+ "										</div>\r\n"
									+ "										<div class=\"cart__btn-proceed-checkout-dt\">\r\n"
									+ "											<button type=\"submit\" class=\"button btn btn-default cart__btn-proceed-checkout\" id=\"btn-proceed-checkout\" title=\"Thanh toán\"><span class=\"text-payment\">Tra Cứu</span></button>\r\n"
									+ "										</div>\r\n"
									+ "									</div>\r\n"
									+ "								</div>"
									+ "							</div>\r\n"
									+ "						</form>\r\n"
									+ "					</div>\r\n"
									+ "				</div>\r\n"
									+ "			</div>\r\n"
									+ "		</div>\r\n"
									+ "	</div>\r\n"
									+ "	<script>\r\n"
									+ "		function getRndInteger(min, max) {\r\n"
									+ "			  return Math.floor(Math.random() * (max - min + 1) ) + min;\r\n"
									+ "			}\r\n"
									+ "		if(!localStorage.getItem(\"count\")) {\r\n"
									+ "			localStorage.setItem(\"count\", getRndInteger(80,150))\r\n"
									+ "		}\r\n"
									+ "		var x = localStorage.getItem(\"count\")\r\n"
									+ "		$(\"#count-customer\").html(x);\r\n"
									+ "	</script>\r\n"
									+ "			</div>\r\n"
									+ "				</div>\r\n"
									+ "			</div>\r\n"
									+ "		</div>\r\n"
									+ "	</div>");
							}
						}
				else {
					response.getWriter().print("<div class=\"main container cartpcstyle\">\r\n"
							+ "		<div class=\"wrap_background_aside margin-bottom-40\">\r\n"
							+ "			<div class=\"cart-page\">\r\n"
							+ "				<div class=\"drawer__inner\">\r\n"
							+ "					<div class=\"CartPageContainer\">\r\n"
							+ "						<form action=\""+request.getContextPath()+"/public/list-order\" method=\"post\" class=\"cart cartpage container\">\r\n"
							+ "							<div class=\"row1\">\r\n"
							+ "								<div class=\"col-12 col-xl-8 order-1 order-xl-1\">\r\n"
							+ "									<div class=\"ajaxcart__inner ajaxcart__inner--has-fixed-footer cart_body items\">\r\n"
							+ "										<p class=\"title\"><span class=\"text-uppercase\">Giỏ hàng</span><span class=\"total-cart\">(<span class=\"count_item_pr\">0</span>) Sản phẩm<span></span></span></p>\r\n"
							+ "										<div class=\"cart-header-info d-none d-md-flex\">\r\n"
							+ "											<div>Sản phẩm</div><div>Đơn giá</div><div>Số lượng</div><div>Tổng tiền</div>\r\n"
							+ "										</div>				\r\n"
							+ "										<div class=\"items-available\">\r\n"
							+ "											<div class=\"ajaxcart__row cart-item  \">\r\n"
							+ "												<p>Không có đơn hàng hãy đặt hàng</p>\r\n"
							+ "											</div>\r\n"
							+ "										</div>\r\n"
							+ "									</div>\r\n"
							+ "								</div>\r\n"
							+ "								<div class=\"col-12 col-xl-4 order-3 order-xl-2 ajaxcart__wrap-footer\">\r\n"
							+ "									<div class=\"ajaxcart__footer ajaxcart__footer--fixed cart-footer\">\r\n"
							+ "										<div class=\"ajaxcart__subtotal\">\r\n"
							+ "											<div class=\"cart__subtotal\">\r\n"
							+ "												<div class=\"cart__col-6\">Tra cứu đơn hàng: </div>\r\n"
							+ "												<div class=\"text-right cart__totle\"><input type=\"text\" name=\"order_code\" value=\"\" required=\"required\"></div>\r\n"
							+ "											</div>\r\n"
							+ "										</div>\r\n"
							+ "										<div class=\"cart__btn-proceed-checkout-dt\">\r\n"
							+ "											<button type=\"submit\" class=\"button btn btn-default cart__btn-proceed-checkout\" id=\"btn-proceed-checkout\" title=\"Thanh toán\"><span class=\"text-payment\">Tra Cứu</span></button>\r\n"
							+ "										</div>\r\n"
							+ "									</div>\r\n"
							+ "								</div>"
							+ "							</div>\r\n"
							+ "						</form>\r\n"
							+ "					</div>\r\n"
							+ "				</div>\r\n"
							+ "			</div>\r\n"
							+ "		</div>\r\n"
							+ "	</div>\r\n"
							+ "	<script>\r\n"
							+ "		function getRndInteger(min, max) {\r\n"
							+ "			  return Math.floor(Math.random() * (max - min + 1) ) + min;\r\n"
							+ "			}\r\n"
							+ "		if(!localStorage.getItem(\"count\")) {\r\n"
							+ "			localStorage.setItem(\"count\", getRndInteger(80,150))\r\n"
							+ "		}\r\n"
							+ "		var x = localStorage.getItem(\"count\")\r\n"
							+ "		$(\"#count-customer\").html(x);\r\n"
							+ "	</script>\r\n"
							+ "			</div>\r\n"
							+ "				</div>\r\n"
							+ "			</div>\r\n"
							+ "		</div>\r\n"
							+ "	</div>");			
					}
			}
	}

}
